// Curated debate motions for the random picker
window.JCI_MOTIONS = [
  "This house believes social media does more harm than good.",
  "School uniforms should be mandatory in all public schools.",
  "Voting should be compulsory for every citizen.",
  "Universal basic income is the future of work.",
  "Homework should be banned in primary schools.",
  "Animal testing for cosmetics should be illegal worldwide.",
  "Single-use plastics should be banned globally.",
  "AI-generated art should be considered real art.",
  "Space exploration is worth the investment.",
  "Cities should ban private cars from their centres.",
  "Junk food advertising to children should be prohibited.",
  "Public transportation should be free for all.",
  "Genetic engineering of human embryos should be allowed.",
  "Nuclear energy is the best solution to climate change.",
  "Standardized testing should be abolished.",
  "Influencers have a responsibility to promote ethical values.",
  "The voting age should be lowered to 16.",
  "Working from home is better than working in an office.",
  "Cryptocurrency does more harm than good.",
  "Zoos should be closed.",
  "Schools should teach mental health as a core subject.",
  "Cosmetic surgery for under-18s should be banned.",
  "Billionaires should not exist.",
  "Smartphones should be banned in classrooms.",
  "Volunteering should be mandatory for high school students.",
  "Free speech includes the right to offend.",
  "AI will be a net positive for humanity.",
  "Fast fashion brands should be held legally responsible for environmental damage.",
  "Every citizen should serve one year of national community service.",
  "Pineapple belongs on pizza."
];
